var inp,
	buttonPaletteNext,
	buttonPalettePrev,
	cSelectX = 1,
	showBranding = true,
	a = 1,
	output,
	font1,
	txt = 'CREATIVE CODING DAYS 2019',
	fontSize = 100,
	txtInput,
	visualPosY = 810 / 2,
	posterW = 586,
	posterH = 810;
